version: "3.8"

volumes:
  bink-db-pgvector-local:
    name: bink-db-pgvector-local
  bink-redis-local:
    name: bink-redis-local

services:
  bink-db-pgvector:
    container_name: bink-db-pgvector
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - bink-db-pgvector-local:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bink-redis:
    container_name: bink-redis
    image: redis:7-alpine
    volumes:
      - bink-redis-local:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
