version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "3000:3000"
    env_file:
      - apps/api/.env
    depends_on:
      - bink-db
      - bink-redis
    logging:
      driver: "fluentd"
      options:
        tag: "docker.{{.Name}}"
    networks:
      - bink-network

  ranj:
    container_name: ranj
    build:
      context: .
      dockerfile: docker/Dockerfile.ranj
    env_file:
      - apps/ranj/.env
    depends_on:
      - bink-db
      - bink-redis
    logging:
      driver: "fluentd"
      options:
        tag: "docker.{{.Name}}"
    networks:
      - bink-network

  client:
    container_name: client
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "80:80"
    networks:
      - bink-network

  bink-db:
    container_name: bink-db
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - bink-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bink-network

  bink-redis:
    container_name: bink-redis
    image: redis:7-alpine
    volumes:
      - bink-redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - bink-network

volumes:
  bink-db:
    name: bink-db
  bink-redis:
    name: bink-redis

networks:
  bink-network:
    external: true
