/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    "bg-[#EF4444]",
    "bg-[#F97316]",
    "bg-[#F59E0B]",
    "bg-[#84CC16]",
    "bg-[#10B981]",
    "bg-[#06B6D4]",
    "bg-[#3B82F6]",
    "bg-[#6366F1]",
    "bg-[#8B5CF6]",
    "bg-[#EC4899]",
    "border-[#EF4444]",
    "border-[#F97316]",
    "border-[#F59E0B]",
    "border-[#84CC16]",
    "border-[#10B981]",
    "border-[#06B6D4]",
    "border-[#3B82F6]",
    "border-[#6366F1]",
    "border-[#8B5CF6]",
    "border-[#EC4899]",
    "bg-[#EF4444]/40",
    "bg-[#F97316]/40",
    "bg-[#F59E0B]/40",
    "bg-[#84CC16]/40",
    "bg-[#10B981]/40",
    "bg-[#06B6D4]/40",
    "bg-[#3B82F6]/40",
    "bg-[#6366F1]/40",
    "bg-[#8B5CF6]/40",
    "bg-[#EC4899]/40",
    "border-[#EF4444]/20",
    "border-[#F97316]/20",
    "border-[#F59E0B]/20",
    "border-[#84CC16]/20",
    "border-[#10B981]/20",
    "border-[#06B6D4]/20",
    "border-[#3B82F6]/20",
    "border-[#6366F1]/20",
    "border-[#8B5CF6]/20",
    "border-[#EC4899]/20",
    "bg-[#EF4444]/80",
    "bg-[#F97316]/80",
    "bg-[#F59E0B]/80",
    "bg-[#84CC16]/80",
    "bg-[#10B981]/80",
    "bg-[#06B6D4]/80",
    "bg-[#3B82F6]/80",
    "bg-[#6366F1]/80",
    "bg-[#8B5CF6]/80",
    "bg-[#EC4899]/80",
  ],
};
