FROM nginx:alpine

COPY apps/landing/index.html /usr/share/nginx/html/index.html.template
COPY docker/nginx.landing.conf /etc/nginx/conf.d/default.conf
COPY docker/landing-entrypoint.sh /docker-entrypoint.d/40-render-landing.sh

RUN chmod +x /docker-entrypoint.d/40-render-landing.sh
