version: '3'
services:
  fluentd:
    image: fluent/fluentd:v1.16.5-1.0
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - bink-network
    restart: unless-stopped

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "local@mail.com"
      ZO_ROOT_USER_PASSWORD: "local"
      ZO_INGEST_ALLOWED_UPTO: "48"
      ZO_PAYLOAD_LIMIT: "2000000000"
      ZO_JSON_LIMIT: "2000000000"
    ports:
      - "5080:5080"
    volumes:
      - ./data:/data
    networks:
      - bink-network

networks:
  bink-network:
    external: true

volumes:
  data: